config/routes.rb
RailsgirlsNola::Application.routes.draw do
  get "welcome/index"
  get "/resources" => "welcome#index" # no longer it's own page, but still directing for it.
  get "/graduates" => "welcome#graduates"
  namespace :slides do
    #get "test"
    get "ux_design"
    get "try_ruby"
    get "workshop"
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  layout 'slides'
  def test
  end
  def ux_design
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def resources
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Girls NOLA</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :modernizr %>
  <link rel="shortcut icon" href="favicon.png">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>
  <hr>
  <div class='row'>
    <div class='columns small-12'>
      <h6>
        Rails Girls New Orleans is run by
        <%= link_to 'New Orleans Women in Technology', 'http://www.neworleanswit.org/' %>
        and
        <%= link_to 'Iconoclast Labs.', 'http://www.iconoclastlabs.com' %>
      </h6>
    </div>
  </div>
  <div class='row'>
    <div class='columns small-12 '>
      <h6>Questions? Comments? Contact us
        <%= link_to "@NewOrleansWIT", 'https://twitter.com/NewOrleansWIT' %>
        or
        <%= link_to "@iconoclastlabs", 'http://www.twitter.com/iconoclastlabs' %>
      </h6>
    </div>
  </div>

</footer>
<script>
  $(function() {
    $(document).foundation();
  });
</script>
</body>
</html>

app/views/layouts/slides.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= yield :head %>

    <meta name="description" content="A framework for easily creating beautiful presentations using HTML">
    <meta name="author" content="Iconoclast Labs">

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- <link rel="stylesheet" href="css/reveal.min.css"> -->
    <%= stylesheet_link_tag("reveal.min", :media => "screen, projection") %>
    <%= stylesheet_link_tag "theme/solarized.css"%>
    <%= stylesheet_link_tag "zenburn" %>


    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "reveal.min" %>
    <%= javascript_include_tag "head.min.js" %>
    <%= javascript_include_tag "slides/ux_design" %>
    <%= stylesheet_link_tag("print/pdf.css", :media => 'print') %>

    <link rel="shortcut icon" href="../favicon.png">
    <!--[if lt IE 9]>
    <script src="html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="reveal">

      <!-- Any section element inside of this container is displayed as a slide -->
      <div class="slides">
        <%= yield %>
      </div>

    </div>



    <script>

      // Full list of configuration options available here:
      // https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,

        theme: Reveal.getQueryHash().theme, // available themes are in /css/theme
        transition: Reveal.getQueryHash().transition || 'default', // default/cube/page/concave/zoom/linear/fade/none

        // Parallax scrolling
        // parallaxBackgroundImage: 'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg',
        // parallaxBackgroundSize: '2100px 900px',

        // Optional libraries used to extend on reveal.js
        dependencies: [
          { src: '../assets/classList.js', condition: function() { return !document.body.classList; } },
          { src: '../assets/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
          { src: '../assets/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
          { src: '../assets/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
          { src: '../assets/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
          { src: '../assets/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }
        ]
      });

    </script>

  </body>
</html>

app/views/shared/_about.html.haml
#about.row
  .row
    .columns.small-12
      %a{name:"About"}
      %h2.nav_section.columns.small-12{:'data-magellan-destination'=>"about"}About
  .columns.small-12.medium-6
    .row
      %h6.columns.small-12.large-10.large-offset-1 Rails Girls is a free Ruby-on-Rails workshop to introduce absolute beginners to the world of programming and web development.
    .row
      %h6.columns.small-12.large-10.large-offset-1 Rails Girls aims to give the tools to enthusiastic girls and women to build their ideas themselves.
  .columns.small-12.medium-5.medium-offset-1
    .panel
      .row
        %h6.columns.small-12.large-10.large-offset-1 Are you a girl who wants to learn Rails?
        %h6.columns.small-12.large-10.large-offset-1
          .button.disabled
            Apply Here
          -#= link_to 'Apply Here', 'https://docs.google.com/forms/d/1U3Xp9ZDRwVs-RABN7WGWbMU_rLFYzawZoy8sJ6Z3VCs/viewform', class: 'button'
      .row
        %h6.columns.small-12.large-10.large-offset-1 Interested in being a coach?
        %h6.columns.small-12.large-10.large-offset-1
          .button.disabled
            Apply Here
          -#= link_to 'Apply Here', 'https://docs.google.com/forms/d/1A1F9a9UFn58xgeqFcvtPT4gBnvbGqOeGLv9_1HJhd6E/viewform', class: 'button'
      .alert-box.alert.radius{:'data-alert' => ''}
        %h5 Wow!

        %h6 We've filled all available coach and participant slots.
        %h6 Rails Girls will surely happen again soon, be sure to check back for updates.

app/views/shared/_location.html.haml
#location.row
  .columns.small-12
    %a{name:"location"}
    %h2.nav_section.columns.small-12{:'data-magellan-destination'=>"location"}Location
    .row
      .columns.small-12.large-5.large-offset-1.medium-6
        %iframe{src: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3457.128613202553!2d-90.06891399999999!3d29.946979000000002!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x715cbe73e62c0563!2siSeatz!5e0!3m2!1sen!2sus!4v1410896524842", width: "400", height: "300", frameborder: "0", style: "border:0"}
      .columns.small-11.small-offset-1.large-5.large-offset-1.medium-5
        %h4
          iSeatz
        %h5
          643 Magazine St #100
        %h5
          New Orleans, LA 70130

app/views/shared/_navigation.html.haml
.row
  .columns.small-12.medium-8.large-8.small-centered{style: "margin-top: 10px;"}
    %div{:'data-magellan-expedition' => "fixed"}
      %dl.railsgirls-sub-nav.small-centered
        %dd{:'data-magellan-arrival' => "title"}
        %dd{:'data-magellan-arrival' => "about"}
          = link_to 'About', root_path + '#about'
        %dd{:'data-magellan-arrival' => "location"}
          = link_to 'Location', root_path + '#location'
        %dd{:'data-magellan-arrival' => "schedule"}
          = link_to 'Schedule', root_path + '#schedule'
        %dd{:'data-magellan-arrival' => "resources"}
          = link_to 'Resources', root_path + "#resources"
        %dd
          = link_to 'Graduates', graduates_path + "#graduates"          

app/views/shared/_resources.html.haml
.row
  .columns.small-12.large-12
    %a{name:"resources"}
    %h2.nav_section.columns.small-12{:'data-magellan-destination'=>"resources"} Rails Girls NOLA Resources
  .columns.small-12.large-12
    .panel
      %h3.subheader
        Installs
        %ul
          %li
            = link_to "Rails Girls Machine and Instructions", "https://github.com/IconoclastLabs/railsgirls_machine"
            %ul
              %li
                = link_to "If Your Machine Can't Support Virtualization - Use Rails Installer", "http://railsinstaller.org/en"
          %li
            = link_to "Sublime Text Editor", "http://www.sublimetext.com/2"
          %li
            = link_to "Install Git", "http://git-scm.com/book/en/Getting-Started-Installing-Git"
            %ul
              %li
                = link_to "Follow Instructions to Generate your SSH Keys", "https://help.github.com/articles/generating-ssh-keys"
          %li
            = link_to "Install Heroku Toolbelt", "https://toolbelt.heroku.com/"
          %li
            = link_to "Install Hub for Git", "http://hub.github.com/"
          %li
            Install Visual GitHub Interface
            %ul
              %li
                = link_to "Windows GitHub", "https://windows.github.com/"
              %li
                = link_to "Mac GitHub", "https://mac.github.com/"
    .panel
      %h3.subheader
        Guides
        %ul
          %li
            Find Terminal and Command Prompt
            %ul
              %li
                = link_to "Command Prompt for Windows", "http://www.computerhope.com/issues/chdos.htm"
              %li
                = link_to "Terminal for Mac", "http://www.youtube.com/watch?v=zw7Nd67_aFw"
              %li
                = link_to "Terminal for Ubuntu", "http://www.wikihow.com/Open-a-Terminal-Window-in-Ubuntu"
    .panel
      %h3.subheader
        Slides
        %ul
          %li
            = link_to "UX Design Workshop Slides", slides_ux_design_path, target: "_blank"
          %li
            = link_to "Try Ruby Slides", slides_try_ruby_path, target: "_blank"
          %li
            = link_to "Main Workshop Slides", slides_workshop_path, target: "_blank"
          %li
            = link_to "Rails Girls 2.0", "http://slides.com/gantlaborde/deck#/", target: "_blank"
    .panel
      %h3.subheader
        Source Code
        %ul
          %li
            = link_to "Source code to this site (RailsGirlsNola)", "https://github.com/IconoclastLabs/railsgirls_nola"

app/views/shared/_schedule.html.haml
#schedule.row
  .columns.small-10
    %a{name:"schedule"}
    %h2.nav_section.columns.small-12{:'data-magellan-destination'=>"schedule"}Schedule

    %h3.subheader
      Friday, February 19
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          8:00pm - 9:00pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Installation Party
        .row
          %h6 Get to know the attendees a little bit before hand. Bring your laptop if you can and we'll work through installing whatever is needed for you.
    %h3.subheader
      Saturday, February 20
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          9:30am - 10:00am
      .columns.small-6.large-6.medium-6
        .row
          %h4 Doors Open
        .row
          %h6 Get ready and handle any last minute issues for the workshop.
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          10:00am - 10:30am
      .columns.small-6.large-6.medium-6
        .row
          %h4 Welcome
        .row
          %h6 Outline of the day, review Rails, &amp; create teams.
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          10:30am - 11:30am
      .columns.small-6.large-6.medium-6
        .row
          %h4 Learning Git + Bio Break
        -#.row
          %h6
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          11:40am - 12:30pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Ruby Warrior
        .row
          %h6 Let's get coding as a Team with Git!
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          12:30pm - 1:15pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Lunch
        -#.row
          %h6
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          1:15pm - 1:30pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Review Ruby Warrior Teams - Pick Winning Team
        .row
          %h6 Show which team won and let them explain their strategy.
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          1:30pm - 1:45pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Review Ruby, introduce JavaScript
        .row
          %h6 Get to know where this all fits in Rails and more
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          1:45pm - 2:45pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Code Combat + Bio Break
        .row
          %h6 Start learning javascript.
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          3:00pm - 3:30pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Review JavaScript, introduce CoffeeScript, introduce Hubot
        .row
          %h6 Get to know where this all fits in Rails and more
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          3:30pm - 4:30pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 CoffeeScript your Hubot
        .row
          %h6 As a team, use Git to add fun features to your Hubot in chat
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          4:30pm - 5:00pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 OpenSource needs you as much as you need it!
        .row
          %h6 What has OS done lately? What can it do?
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          5:00pm - 5:30pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Show and Tell
        .row
          %h6 Everyone shows their HuBots, the coaches vote on who wins.
    .row
      .columns.small-5.large-offset-3.large-1.medium-offset-3.medium-1
        .label.secondary
          6:00pm
      .columns.small-6.large-6.medium-6
        .row
          %h4 Party!
        .row
          %h6 Paid by Grok &amp; Banter

app/views/slides/test.html.erb
<section>
          <h1>Reveal.js</h1>
          <h3>HTML Presentations Made Easy</h3>
          <p>
            <small>Created by <a href="http://hakim.se">Hakim El Hattab</a> / <a href="http://twitter.com/hakimel">@hakimel</a></small>
          </p>
        </section>

        <section>
          <h2>Heads Up</h2>
          <p>
            reveal.js is a framework for easily creating beautiful presentations using HTML. You'll need a browser with
            support for CSS 3D transforms to see it in its full glory.
          </p>

          <aside class="notes">
            Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
          </aside>
        </section>

        <!-- Example of nested vertical slides -->
        <section>
          <section>
            <h2>Vertical Slides</h2>
            <p>
              Slides can be nested inside of other slides,
              try pressing <a href="#" class="navigate-down">down</a>.
            </p>
            <a href="#" class="image navigate-down">
              <img width="178" height="238" src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow">
            </a>
          </section>
          <section>
            <h2>Basement Level 1</h2>
            <p>Press down or up to navigate.</p>
          </section>
          <section>
            <h2>Basement Level 2</h2>
            <p>Cornify</p>
            <a class="test" href="http://cornify.com">
              <img width="280" height="326" src="https://s3.amazonaws.com/hakim-static/reveal-js/cornify.gif" alt="Unicorn">
            </a>
          </section>
          <section>
            <h2>Basement Level 3</h2>
            <p>That's it, time to go back up.</p>
            <a href="#/2" class="image">
              <img width="178" height="238" src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="-webkit-transform: rotate(180deg);">
            </a>
          </section>
        </section>

        <section>
          <h2>Slides</h2>
          <p>
            Not a coder? No problem. There's a fully-featured visual editor for authoring these, try it out at <a href="http://slid.es" target="_blank">http://slid.es</a>.
          </p>
        </section>

        <section>
          <h2>Point of View</h2>
          <p>
            Press <strong>ESC</strong> to enter the slide overview.
          </p>
          <p>
            Hold down alt and click on any element to zoom in on it using <a href="http://lab.hakim.se/zoom-js">zoom.js</a>. Alt + click anywhere to zoom back out.
          </p>
        </section>

        <section>
          <h2>Works in Mobile Safari</h2>
          <p>
            Try it out! You can swipe through the slides and pinch your way to the overview.
          </p>
        </section>

        <section>
          <h2>Marvelous Unordered List</h2>
          <ul>
            <li>No order here</li>
            <li>Or here</li>
            <li>Or here</li>
            <li>Or here</li>
          </ul>
        </section>

        <section>
          <h2>Fantastic Ordered List</h2>
          <ol>
            <li>One is smaller than...</li>
            <li>Two is smaller than...</li>
            <li>Three!</li>
          </ol>
        </section>

        <section data-markdown>
          <script type="text/template">
            ## Markdown support

            For those of you who like that sort of thing. Instructions and a bit more info available [here](https://github.com/hakimel/reveal.js#markdown).

            ```
            <section data-markdown>
              ## Markdown support

              For those of you who like that sort of thing.
              Instructions and a bit more info available [here](https://github.com/hakimel/reveal.js#markdown).
            </section>
            ```
          </script>
        </section>

        <section id="transitions">
          <h2>Transition Styles</h2>
          <p>
            You can select from different transitions, like: <br>
            <a href="?transition=cube#/transitions">Cube</a> -
            <a href="?transition=page#/transitions">Page</a> -
            <a href="?transition=concave#/transitions">Concave</a> -
            <a href="?transition=zoom#/transitions">Zoom</a> -
            <a href="?transition=linear#/transitions">Linear</a> -
            <a href="?transition=fade#/transitions">Fade</a> -
            <a href="?transition=none#/transitions">None</a> -
            <a href="?#/transitions">Default</a>
          </p>
        </section>

        <section id="themes">
          <h2>Themes</h2>
          <p>
            Reveal.js comes with a few themes built in: <br>
            <a href="?#/themes">Default</a> -
            <a href="?theme=sky#/themes">Sky</a> -
            <a href="?theme=beige#/themes">Beige</a> -
            <a href="?theme=simple#/themes">Simple</a> -
            <a href="?theme=serif#/themes">Serif</a> -
            <a href="?theme=night#/themes">Night</a> <br>
            <a href="?theme=moon#/themes">Moon</a> -
            <a href="?theme=solarized#/themes">Solarized</a>
          </p>
          <p>
            <small>
              * Theme demos are loaded after the presentation which leads to flicker. In production you should load your theme in the <code>&lt;head&gt;</code> using a <code>&lt;link&gt;</code>.
            </small>
          </p>
        </section>

        <section>
          <h2>Global State</h2>
          <p>
            Set <code>data-state="something"</code> on a slide and <code>"something"</code>
            will be added as a class to the document element when the slide is open. This lets you
            apply broader style changes, like switching the background.
          </p>
        </section>

        <section data-state="customevent">
          <h2>Custom Events</h2>
          <p>
            Additionally custom events can be triggered on a per slide basis by binding to the <code>data-state</code> name.
          </p>
          <pre><code data-trim contenteditable style="font-size: 18px; margin-top: 20px;">
Reveal.addEventListener( 'customevent', function() {
  console.log( '"customevent" has fired' );
} );
          </code></pre>
        </section>

        <section>
          <section data-background="#007777">
            <h2>Slide Backgrounds</h2>
            <p>
              Set <code>data-background="#007777"</code> on a slide to change the full page background to the given color. All CSS color formats are supported.
            </p>
            <a href="#" class="image navigate-down">
              <img width="178" height="238" src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow">
            </a>
          </section>
          <section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png">
            <h2>Image Backgrounds</h2>
            <pre><code>&lt;section data-background="image.png"&gt;</code></pre>
          </section>
          <section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" data-background-repeat="repeat" data-background-size="100px">
            <h2>Repeated Image Backgrounds</h2>
            <pre><code style="word-wrap: break-word;">&lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&gt;</code></pre>
          </section>
        </section>

        <section data-transition="linear" data-background="#4d7e65" data-background-transition="slide">
          <h2>Background Transitions</h2>
          <p>
            Pass reveal.js the <code>backgroundTransition: 'slide'</code> config argument to make backgrounds slide rather than fade.
          </p>
        </section>

        <section data-transition="linear" data-background="#8c4738" data-background-transition="slide">
          <h2>Background Transition Override</h2>
          <p>
            You can override background transitions per slide by using <code>data-background-transition="slide"</code>.
          </p>
        </section>

        <section>
          <h2>Clever Quotes</h2>
          <p>
            These guys come in two forms, inline: <q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations">
            &ldquo;The nice thing about standards is that there are so many to choose from&rdquo;</q> and block:
          </p>
          <blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations">
            &ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
            reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&rdquo;
          </blockquote>
        </section>

        <section>
          <h2>Pretty Code</h2>
          <pre><code data-trim contenteditable>
function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
          </code></pre>
          <p>Courtesy of <a href="http://softwaremaniacs.org/soft/highlight/en/description/">highlight.js</a>.</p>
        </section>

        <section>
          <h2>Intergalactic Interconnections</h2>
          <p>
            You can link between slides internally,
            <a href="#/2/3">like this</a>.
          </p>
        </section>

        <section>
          <section id="fragments">
            <h2>Fragmented Views</h2>
            <p>Hit the next arrow...</p>
            <p class="fragment">... to step through ...</p>
            <ol>
              <li class="fragment"><code>any type</code></li>
              <li class="fragment"><em>of view</em></li>
              <li class="fragment"><strong>fragments</strong></li>
            </ol>

            <aside class="notes">
              This slide has fragments which are also stepped through in the notes window.
            </aside>
          </section>
          <section>
            <h2>Fragment Styles</h2>
            <p>There's a few styles of fragments, like:</p>
            <p class="fragment grow">grow</p>
            <p class="fragment shrink">shrink</p>
            <p class="fragment roll-in">roll-in</p>
            <p class="fragment fade-out">fade-out</p>
            <p class="fragment highlight-red">highlight-red</p>
            <p class="fragment highlight-green">highlight-green</p>
            <p class="fragment highlight-blue">highlight-blue</p>
            <p class="fragment current-visible">current-visible</p>
            <p class="fragment highlight-current-blue">highlight-current-blue</p>
          </section>
        </section>

        <section>
          <h2>Spectacular image!</h2>
          <a class="image" href="http://lab.hakim.se/meny/" target="_blank">
            <img width="320" height="299" src="http://s3.amazonaws.com/hakim-static/portfolio/images/meny.png" alt="Meny">
          </a>
        </section>

        <section>
          <h2>Export to PDF</h2>
          <p>Presentations can be <a href="https://github.com/hakimel/reveal.js#pdf-export">exported to PDF</a>, below is an example that's been uploaded to SlideShare.</p>

        </section>

        <section>
          <h2>Take a Moment</h2>
          <p>
            Press b or period on your keyboard to enter the 'paused' mode. This mode is helpful when you want to take distracting slides off the screen
            during a presentation.
          </p>
        </section>

        <section>
          <h2>Stellar Links</h2>
          <ul>
            <li><a href="http://slid.es">Try the online editor</a></li>
            <li><a href="https://github.com/hakimel/reveal.js">Source code on GitHub</a></li>
            <li><a href="http://twitter.com/hakimel">Follow me on Twitter</a></li>
          </ul>
        </section>

        <section>
          <h1>THE END</h1>
          <h3>BY Hakim El Hattab / hakim.se</h3>
        </section>

app/views/welcome/index.html.haml
.row.top_logo
  .columns.small-10.medium-8.large-6.small-centered
    %a{name:"Title"}
    = image_tag 'Logo.png', :'data-magellan-destination'=>"title"

= render "shared/navigation"

= render "shared/about"
%hr
= render "shared/location"
%hr
= render "shared/schedule"
%hr
= render "shared/resources"